# Prose check (plan WP8): descriptions <= 3 sentences, sentences <= 25 words.
# Usage: Rscript dev/sharpen-prose.R [package_root]   (default: rcomplex-dev, or . inside it)
args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) args[1] else if (dir.exists("rcomplex-dev")) "rcomplex-dev" else "."
max_sent <- 3L
max_words <- 25L
hits <- 0L

split_sentences <- function(txt) {
  txt <- gsub("\\b(e\\.g|i\\.e|vs|et al|cf|etc|approx)\\.", "\\1<dot>", txt)
  txt <- gsub("\\.\\.\\.", "<dot><dot><dot>", txt)
  s <- trimws(unlist(strsplit(txt, "(?<=[.?!])\\s+", perl = TRUE)))
  s[nzchar(s)]
}

report <- function(file, line, what, text) {
  hits <<- hits + 1L
  cat(sprintf("%s:%d: %s\n", file, line, what))
  if (!is.null(text)) cat("    ", substr(text, 1, 100), "\n", sep = "")
}

check_text <- function(file, line, txt, is_description) {
  s <- split_sentences(txt)
  if (is_description && length(s) > max_sent) {
    report(file, line, sprintf("description has %d sentences (max %d)",
                               length(s), max_sent), s[1])
  }
  for (x in s) {
    n <- length(strsplit(x, "\\s+")[[1]])
    if (n > max_words) {
      report(file, line, sprintf("sentence has %d words (max %d)", n, max_words),
             x)
    }
  }
}

# Roxygen blocks of one R file: list of (line, text) per description.
descriptions <- function(path) {
  x <- readLines(path, warn = FALSE)
  is_rox <- grepl("^#'", x)
  out <- list()
  i <- 1L
  while (i <= length(x)) {
    if (!is_rox[i]) { i <- i + 1L; next }
    j <- i
    while (j < length(x) && is_rox[j + 1L]) j <- j + 1L
    b <- sub("^#' ?", "", x[i:j])
    ln <- i:j
    tag <- grepl("^@", b)
    if (any(grepl("^@noRd", b))) { i <- j + 1L; next }  # no Rd output
    # section id of each line: leading untagged = "", then tag names
    sec <- character(length(b)); cur <- ""
    for (k in seq_along(b)) {
      if (tag[k]) cur <- sub("^@(\\w+).*", "\\1", b[k])
      sec[k] <- cur
    }
    lead <- which(sec == "")
    desc_idx <- which(sec == "description")
    if (length(desc_idx)) {
      txt <- paste(sub("^@description\\s*", "", b[desc_idx]), collapse = " ")
      out[[length(out) + 1L]] <- list(line = ln[desc_idx[1]], text = txt)
    } else if (length(lead)) {
      paras <- split(lead, cumsum(c(TRUE, diff(lead) != 1L |
                                      !nzchar(trimws(b[lead[-1L]])))))
      # split on blank lines
      blank <- !nzchar(trimws(b[lead]))
      grp <- cumsum(blank)
      paras <- split(lead[!blank], grp[!blank])
      has_title <- any(sec == "title")
      skip <- if (has_title) 0L else 1L
      if (length(paras) > skip) {
        idx <- paras[[skip + 1L]]  # one paragraph; the rest is @details
        out[[length(out) + 1L]] <- list(
          line = ln[idx[1]], text = paste(b[idx], collapse = " "))
      }
    }
    i <- j + 1L
  }
  out
}

# Prose of a markdown file, skipping YAML and fenced code.
prose_lines <- function(path) {
  x <- readLines(path, warn = FALSE)
  keep <- rep(TRUE, length(x))
  fence <- cumsum(grepl("^\\s*(```|~~~)", x))
  keep[fence %% 2L == 1L | grepl("^\\s*(```|~~~)", x)] <- FALSE
  if (length(x) && x[1] == "---") {
    end <- which(x[-1] == "---")[1] + 1L
    if (!is.na(end)) keep[1:end] <- FALSE
  }
  keep[grepl("^\\s*(#|\\||<|!\\[|\\[.*\\]:)", x)] <- FALSE
  list(x = x, keep = keep)
}

rfiles <- list.files(file.path(root, "R"), "\\.R$", full.names = TRUE)
if (!length(rfiles)) cat("missing: ", file.path(root, "R"), "\n", sep = "")
for (f in rfiles) {
  if (grepl("Generated by", readLines(f, 1L))) next  # RcppExports.R
  for (d in descriptions(f)) check_text(f, d$line, d$text, TRUE)
}

for (f in file.path(root, c("README.md", "vignettes/quickstart.Rmd"))) {
  if (!file.exists(f)) { cat("missing: ", f, "\n", sep = ""); next }
  p <- prose_lines(f)
  i <- 1L
  while (i <= length(p$x)) {
    if (!p$keep[i] || !nzchar(trimws(p$x[i]))) { i <- i + 1L; next }
    j <- i
    while (j < length(p$x) && p$keep[j + 1L] && nzchar(trimws(p$x[j + 1L]))) {
      j <- j + 1L
    }
    txt <- gsub("^\\s*([-*]|\\d+\\.)\\s+", "", p$x[i:j])
    check_text(f, i, paste(txt, collapse = " "), FALSE)
    i <- j + 1L
  }
}

if (hits) {
  cat(sprintf("%d hit(s)\n", hits))
  quit(status = 1L)
}
cat("sharpen-prose: 0 hits\n")
