# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply CLR transformation to a correlation matrix
#'
#' Normalizes a correlation matrix using the Context Likelihood Ratio (CLR)
#' transformation (Faith et al. 2007). Computes row z-scores, clamps negatives
#' to zero, and combines row and column z-scores.
#'
#' @param cor_matrix Symmetric correlation matrix (n x n)
#' @param n_cores Number of OpenMP threads (default: 1)
#' @return CLR-transformed matrix (n x n), symmetric, non-negative
#'
#' @details
#' The CLR transformation:
#' \preformatted{
#' z_row(i,j) = (cor(i,j) - mean(row_i)) / sd(row_i)
#' z_col(i,j) = (cor(i,j) - mean(col_j)) / sd(col_j)
#' CLR(i,j) = sqrt(max(0, z_row)^2 + max(0, z_col)^2)
#' }
#'
#' This matches the original RComPlEx Rmd CLR implementation which uses
#' R's scale() function (column-wise z-scoring on the symmetric matrix,
#' equivalent to row-wise z-scoring due to symmetry).
#'
#' @keywords internal
apply_clr_to_cor_cpp <- function(cor_matrix, n_cores = 1L) {
    .Call(`_rcomplex_apply_clr_to_cor_cpp`, cor_matrix, n_cores)
}

#' Compute density threshold from a symmetric matrix
#'
#' Extracts the upper triangle (excluding diagonal) and finds the value at
#' the given density percentile using O(n) partial sort.
#'
#' @param mat Symmetric matrix (n x n)
#' @param density Fraction of top edges to keep (e.g., 0.03 for 3%)
#' @return The threshold value such that `density` fraction of upper triangle
#'   values are >= the threshold
#'
#' @keywords internal
density_threshold_cpp <- function(mat, density) {
    .Call(`_rcomplex_density_threshold_cpp`, mat, density)
}

#' Cached mutual rank transformation
#'
#' Transforms a correlation matrix using mutual rank normalization.
#'
#' @param sim Symmetric correlation/similarity matrix (n x n)
#' @param log_transform If FALSE (default), uses raw mutual rank with ascending
#'   ranks (original Rmd formula). If TRUE, applies Obayashi & Kinoshita (2009)
#'   log-normalized formula with descending ranks (values in 0 to 1 range).
#' @param n_cores Number of OpenMP threads (default: 1)
#' @return Mutual rank normalized matrix (n x n)
#'
#' @details
#' When `log_transform = TRUE`:
#' \deqn{S_{ij} = 1 - \log(\sqrt{R_{ij} \cdot R_{ji}}) / \log(n)}
#' where ranks are descending (highest correlation = rank 1).
#'
#' When `log_transform = FALSE`:
#' \deqn{MR_{ij} = \sqrt{R_{ij} \cdot R_{ji}}}
#' where ranks are ascending (lowest correlation = rank 1), matching the
#' original RComPlEx R Markdown formula.
#'
#' @keywords internal
mutual_rank_transform_cached_cpp <- function(sim, log_transform = FALSE, n_cores = 1L) {
    .Call(`_rcomplex_mutual_rank_transform_cached_cpp`, sim, log_transform, n_cores)
}

#' In-place mutual rank transformation
#'
#' Overwrites `sim` with its mutual rank transform without allocating any
#' n x n temporaries. Pass 1 clamps each column to \[-1, 1\], optionally takes
#' absolute values, and replaces the column by its average ranks. Pass 2
#' replaces each pair (i, j) by sqrt(R_ij * R_ji) (log-normalized when
#' `log_transform`) and sets the diagonal to 0. Same formulas and tie
#' handling as [mutual_rank_transform_cached_cpp()], which is kept as the
#' reference implementation.
#'
#' @param sim Symmetric correlation/similarity matrix (n x n). Modified in
#'   place: must be a fresh allocation not shared with any other R object,
#'   and must be stored as double (`REALSXP`); any other storage type is an
#'   error, since coercion would silently operate on a copy. Must not
#'   contain `NaN`/`NA` (ranking would be undefined); an error is raised
#'   and the contents of `sim` are then unspecified.
#' @param log_transform If FALSE, raw mutual rank with ascending ranks
#'   (original Rmd formula). If TRUE, Obayashi & Kinoshita (2009)
#'   log-normalized formula with descending ranks (values in 0 to 1 range).
#' @param abs_cor If TRUE, take absolute values before ranking.
#' @param n_cores Number of OpenMP threads
#' @return Invisible `NULL`; `sim` is modified in place.
#'
#' @keywords internal
mutual_rank_inplace_cpp <- function(sim, log_transform, abs_cor, n_cores) {
    invisible(.Call(`_rcomplex_mutual_rank_inplace_cpp`, sim, log_transform, abs_cor, n_cores))
}

#' Blockwise sparse mutual-rank network
#'
#' @param zt Standardised expression (samples x genes) such that
#'   `crossprod(zt)` is the correlation matrix.
#' @param log_transform,abs_cor As in [mutual_rank_inplace_cpp()].
#' @param density,store_density Analysis and store densities.
#' @param block_size Columns per correlation block.
#' @param n_cores Number of OpenMP threads.
#' @return List with dgCMatrix slots `i`, `p`, `x`, the `threshold` and
#'   `store_threshold`, the number of joined candidate pairs
#'   `n_candidates`, the rank `fraction` that sufficed and the
#'   `start_fraction` the build began with.
#'
#' @keywords internal
mr_block_network_cpp <- function(zt, log_transform, abs_cor, density, store_density, block_size, n_cores) {
    .Call(`_rcomplex_mr_block_network_cpp`, zt, log_transform, abs_cor, density, store_density, block_size, n_cores)
}

#' Reduce orthogroups by merging correlated paralogs
#'
#' For each HOG with multiple paralogs, computes pairwise Pearson correlation
#' on the expression matrix, clusters with Ward.D2, and merges paralogs
#' whose correlation exceeds \code{cor_threshold} into a single averaged
#' representative.
#'
#' @param expr Numeric matrix (genes x samples). Row order matches gene_ids.
#' @param hog_members List of integer vectors. Each element contains 1-indexed
#'   row positions in \code{expr} for genes belonging to one HOG.
#' @param non_hog_idx Integer vector of 1-indexed row positions for genes
#'   not assigned to any HOG (kept as-is).
#' @param cor_threshold Pearson correlation threshold for merging (default 0.7).
#' @return List with: expr_matrix (reduced matrix), out_row_source (1-indexed
#'   original row for each output row), map_from / map_to (1-indexed gene
#'   mapping), n_original, n_reduced, n_merged.
#' @keywords internal
reduce_orthogroups_cpp <- function(expr, hog_members, non_hog_idx, cor_threshold) {
    .Call(`_rcomplex_reduce_orthogroups_cpp`, expr, hog_members, non_hog_idx, cor_threshold)
}

#' Extract dgCMatrix slots from a dense matrix at a store threshold
#'
#' Keeps the off-diagonal entries `>= thr` of both triangles and returns
#' the column-compressed slots of the corresponding `dgCMatrix`: 0-based
#' row indices `i` (ascending within each column), column pointers `p`
#' (length n + 1) and values `x`.
#'
#' @param m Dense numeric matrix (n x n)
#' @param thr Store threshold; entries below it are discarded
#' @param n_cores Number of threads for parallel computation (default 1)
#' @return List with integer vectors `i` and `p` and numeric vector `x`
#'
#' @keywords internal
extract_sparse_cpp <- function(m, thr, n_cores = 1L) {
    .Call(`_rcomplex_extract_sparse_cpp`, m, thr, n_cores)
}

