// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// apply_clr_to_cor_cpp
arma::mat apply_clr_to_cor_cpp(const arma::mat& cor_matrix, int n_cores);
RcppExport SEXP _rcomplex_apply_clr_to_cor_cpp(SEXP cor_matrixSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cor_matrix(cor_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_clr_to_cor_cpp(cor_matrix, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// density_threshold_cpp
double density_threshold_cpp(const arma::mat& mat, double density);
RcppExport SEXP _rcomplex_density_threshold_cpp(SEXP matSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type density(densitySEXP);
    rcpp_result_gen = Rcpp::wrap(density_threshold_cpp(mat, density));
    return rcpp_result_gen;
END_RCPP
}
// mutual_rank_transform_cached_cpp
arma::mat mutual_rank_transform_cached_cpp(const arma::mat& sim, bool log_transform, int n_cores);
RcppExport SEXP _rcomplex_mutual_rank_transform_cached_cpp(SEXP simSEXP, SEXP log_transformSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transform(log_transformSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mutual_rank_transform_cached_cpp(sim, log_transform, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mutual_rank_inplace_cpp
void mutual_rank_inplace_cpp(SEXP sim, bool log_transform, bool abs_cor, int n_cores);
RcppExport SEXP _rcomplex_mutual_rank_inplace_cpp(SEXP simSEXP, SEXP log_transformSEXP, SEXP abs_corSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transform(log_transformSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_cor(abs_corSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    mutual_rank_inplace_cpp(sim, log_transform, abs_cor, n_cores);
    return R_NilValue;
END_RCPP
}
// mr_block_network_cpp
List mr_block_network_cpp(const arma::mat& zt, bool log_transform, bool abs_cor, double density, double store_density, int block_size, int n_cores);
RcppExport SEXP _rcomplex_mr_block_network_cpp(SEXP ztSEXP, SEXP log_transformSEXP, SEXP abs_corSEXP, SEXP densitySEXP, SEXP store_densitySEXP, SEXP block_sizeSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type zt(ztSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transform(log_transformSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_cor(abs_corSEXP);
    Rcpp::traits::input_parameter< double >::type density(densitySEXP);
    Rcpp::traits::input_parameter< double >::type store_density(store_densitySEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mr_block_network_cpp(zt, log_transform, abs_cor, density, store_density, block_size, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// reduce_orthogroups_cpp
List reduce_orthogroups_cpp(const arma::mat& expr, const List& hog_members, const IntegerVector& non_hog_idx, double cor_threshold);
RcppExport SEXP _rcomplex_reduce_orthogroups_cpp(SEXP exprSEXP, SEXP hog_membersSEXP, SEXP non_hog_idxSEXP, SEXP cor_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< const List& >::type hog_members(hog_membersSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type non_hog_idx(non_hog_idxSEXP);
    Rcpp::traits::input_parameter< double >::type cor_threshold(cor_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_orthogroups_cpp(expr, hog_members, non_hog_idx, cor_threshold));
    return rcpp_result_gen;
END_RCPP
}
// extract_sparse_cpp
List extract_sparse_cpp(const arma::mat& m, double thr, int n_cores);
RcppExport SEXP _rcomplex_extract_sparse_cpp(SEXP mSEXP, SEXP thrSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_sparse_cpp(m, thr, n_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcomplex_apply_clr_to_cor_cpp", (DL_FUNC) &_rcomplex_apply_clr_to_cor_cpp, 2},
    {"_rcomplex_density_threshold_cpp", (DL_FUNC) &_rcomplex_density_threshold_cpp, 2},
    {"_rcomplex_mutual_rank_transform_cached_cpp", (DL_FUNC) &_rcomplex_mutual_rank_transform_cached_cpp, 3},
    {"_rcomplex_mutual_rank_inplace_cpp", (DL_FUNC) &_rcomplex_mutual_rank_inplace_cpp, 4},
    {"_rcomplex_mr_block_network_cpp", (DL_FUNC) &_rcomplex_mr_block_network_cpp, 7},
    {"_rcomplex_reduce_orthogroups_cpp", (DL_FUNC) &_rcomplex_reduce_orthogroups_cpp, 4},
    {"_rcomplex_extract_sparse_cpp", (DL_FUNC) &_rcomplex_extract_sparse_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcomplex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
