// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// apply_clr_to_cor_cpp
arma::mat apply_clr_to_cor_cpp(const arma::mat& cor_matrix, int n_cores);
RcppExport SEXP _rcomplex_apply_clr_to_cor_cpp(SEXP cor_matrixSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cor_matrix(cor_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_clr_to_cor_cpp(cor_matrix, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// density_threshold_cpp
double density_threshold_cpp(const arma::mat& mat, double density);
RcppExport SEXP _rcomplex_density_threshold_cpp(SEXP matSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type density(densitySEXP);
    rcpp_result_gen = Rcpp::wrap(density_threshold_cpp(mat, density));
    return rcpp_result_gen;
END_RCPP
}
// hog_permutation_test_cpp
Rcpp::DataFrame hog_permutation_test_cpp(const arma::mat& net1, const arma::mat& net2, double thr1, double thr2, const Rcpp::IntegerVector& ortho_sp1_idx, const Rcpp::IntegerVector& ortho_sp2_idx, const Rcpp::List& hog_sp1_list, const Rcpp::List& hog_sp2_list, bool test_greater, int min_exceedances, int max_permutations, int n_cores);
RcppExport SEXP _rcomplex_hog_permutation_test_cpp(SEXP net1SEXP, SEXP net2SEXP, SEXP thr1SEXP, SEXP thr2SEXP, SEXP ortho_sp1_idxSEXP, SEXP ortho_sp2_idxSEXP, SEXP hog_sp1_listSEXP, SEXP hog_sp2_listSEXP, SEXP test_greaterSEXP, SEXP min_exceedancesSEXP, SEXP max_permutationsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type net1(net1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type net2(net2SEXP);
    Rcpp::traits::input_parameter< double >::type thr1(thr1SEXP);
    Rcpp::traits::input_parameter< double >::type thr2(thr2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp1_idx(ortho_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp2_idx(ortho_sp2_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp1_list(hog_sp1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp2_list(hog_sp2_listSEXP);
    Rcpp::traits::input_parameter< bool >::type test_greater(test_greaterSEXP);
    Rcpp::traits::input_parameter< int >::type min_exceedances(min_exceedancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_permutations(max_permutationsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(hog_permutation_test_cpp(net1, net2, thr1, thr2, ortho_sp1_idx, ortho_sp2_idx, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mutual_rank_transform_cached_cpp
arma::mat mutual_rank_transform_cached_cpp(const arma::mat& sim, bool log_transform, int n_cores);
RcppExport SEXP _rcomplex_mutual_rank_transform_cached_cpp(SEXP simSEXP, SEXP log_transformSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transform(log_transformSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mutual_rank_transform_cached_cpp(sim, log_transform, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// compare_neighborhoods_cpp
Rcpp::DataFrame compare_neighborhoods_cpp(const arma::mat& net1, const arma::mat& net2, double thr1, double thr2, const Rcpp::IntegerVector& pair_sp1_idx, const Rcpp::IntegerVector& pair_sp2_idx, const Rcpp::IntegerVector& ortho_sp1_idx, const Rcpp::IntegerVector& ortho_sp2_idx, int n_cores);
RcppExport SEXP _rcomplex_compare_neighborhoods_cpp(SEXP net1SEXP, SEXP net2SEXP, SEXP thr1SEXP, SEXP thr2SEXP, SEXP pair_sp1_idxSEXP, SEXP pair_sp2_idxSEXP, SEXP ortho_sp1_idxSEXP, SEXP ortho_sp2_idxSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type net1(net1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type net2(net2SEXP);
    Rcpp::traits::input_parameter< double >::type thr1(thr1SEXP);
    Rcpp::traits::input_parameter< double >::type thr2(thr2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_sp1_idx(pair_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_sp2_idx(pair_sp2_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp1_idx(ortho_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp2_idx(ortho_sp2_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_neighborhoods_cpp(net1, net2, thr1, thr2, pair_sp1_idx, pair_sp2_idx, ortho_sp1_idx, ortho_sp2_idx, n_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcomplex_apply_clr_to_cor_cpp", (DL_FUNC) &_rcomplex_apply_clr_to_cor_cpp, 2},
    {"_rcomplex_density_threshold_cpp", (DL_FUNC) &_rcomplex_density_threshold_cpp, 2},
    {"_rcomplex_hog_permutation_test_cpp", (DL_FUNC) &_rcomplex_hog_permutation_test_cpp, 12},
    {"_rcomplex_mutual_rank_transform_cached_cpp", (DL_FUNC) &_rcomplex_mutual_rank_transform_cached_cpp, 3},
    {"_rcomplex_compare_neighborhoods_cpp", (DL_FUNC) &_rcomplex_compare_neighborhoods_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcomplex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
