// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// apply_clr_to_cor_cpp
arma::mat apply_clr_to_cor_cpp(const arma::mat& cor_matrix, int n_cores);
RcppExport SEXP _rcomplex_apply_clr_to_cor_cpp(SEXP cor_matrixSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cor_matrix(cor_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_clr_to_cor_cpp(cor_matrix, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// build_coclassification_cpp
Rcpp::List build_coclassification_cpp(const Rcpp::List& memberships, int n_genes, bool return_excess);
RcppExport SEXP _rcomplex_build_coclassification_cpp(SEXP membershipsSEXP, SEXP n_genesSEXP, SEXP return_excessSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type memberships(membershipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type return_excess(return_excessSEXP);
    rcpp_result_gen = Rcpp::wrap(build_coclassification_cpp(memberships, n_genes, return_excess));
    return rcpp_result_gen;
END_RCPP
}
// build_sparse_coclassification_cpp
Rcpp::List build_sparse_coclassification_cpp(const Rcpp::List& memberships, int n_genes, const Rcpp::IntegerMatrix& edges, int n_cores);
RcppExport SEXP _rcomplex_build_sparse_coclassification_cpp(SEXP membershipsSEXP, SEXP n_genesSEXP, SEXP edgesSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type memberships(membershipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(build_sparse_coclassification_cpp(memberships, n_genes, edges, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// sparse_excess_spectral_norm_cpp
double sparse_excess_spectral_norm_cpp(const Rcpp::List& memberships, int n_genes, const Rcpp::IntegerMatrix& edges, int n_cores);
RcppExport SEXP _rcomplex_sparse_excess_spectral_norm_cpp(SEXP membershipsSEXP, SEXP n_genesSEXP, SEXP edgesSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type memberships(membershipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_excess_spectral_norm_cpp(memberships, n_genes, edges, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// density_threshold_cpp
double density_threshold_cpp(const arma::mat& mat, double density);
RcppExport SEXP _rcomplex_density_threshold_cpp(SEXP matSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type density(densitySEXP);
    rcpp_result_gen = Rcpp::wrap(density_threshold_cpp(mat, density));
    return rcpp_result_gen;
END_RCPP
}
// fe_hog_permutation_test_cpp
Rcpp::DataFrame fe_hog_permutation_test_cpp(const arma::mat& combined, const Rcpp::List& hog_sp1_list, const Rcpp::List& hog_sp2_list, bool test_greater, int min_exceedances, int max_permutations, int n_cores);
RcppExport SEXP _rcomplex_fe_hog_permutation_test_cpp(SEXP combinedSEXP, SEXP hog_sp1_listSEXP, SEXP hog_sp2_listSEXP, SEXP test_greaterSEXP, SEXP min_exceedancesSEXP, SEXP max_permutationsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type combined(combinedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp1_list(hog_sp1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp2_list(hog_sp2_listSEXP);
    Rcpp::traits::input_parameter< bool >::type test_greater(test_greaterSEXP);
    Rcpp::traits::input_parameter< int >::type min_exceedances(min_exceedancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_permutations(max_permutationsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(fe_hog_permutation_test_cpp(combined, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// find_cliques_cpp
Rcpp::List find_cliques_cpp(IntegerVector edge_hog, IntegerVector edge_g1, IntegerVector edge_g2, IntegerVector edge_sp1, IntegerVector edge_sp2, NumericVector edge_qval, NumericVector edge_eff, int n_target_species, int min_species, int n_hogs, int n_genes, int max_genes_per_sp, int max_missing_edges, double w_q, double w_eff);
RcppExport SEXP _rcomplex_find_cliques_cpp(SEXP edge_hogSEXP, SEXP edge_g1SEXP, SEXP edge_g2SEXP, SEXP edge_sp1SEXP, SEXP edge_sp2SEXP, SEXP edge_qvalSEXP, SEXP edge_effSEXP, SEXP n_target_speciesSEXP, SEXP min_speciesSEXP, SEXP n_hogsSEXP, SEXP n_genesSEXP, SEXP max_genes_per_spSEXP, SEXP max_missing_edgesSEXP, SEXP w_qSEXP, SEXP w_effSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type edge_hog(edge_hogSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_g1(edge_g1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_g2(edge_g2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_sp1(edge_sp1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_sp2(edge_sp2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_qval(edge_qvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_eff(edge_effSEXP);
    Rcpp::traits::input_parameter< int >::type n_target_species(n_target_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type min_species(min_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type n_hogs(n_hogsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type max_genes_per_sp(max_genes_per_spSEXP);
    Rcpp::traits::input_parameter< int >::type max_missing_edges(max_missing_edgesSEXP);
    Rcpp::traits::input_parameter< double >::type w_q(w_qSEXP);
    Rcpp::traits::input_parameter< double >::type w_eff(w_effSEXP);
    rcpp_result_gen = Rcpp::wrap(find_cliques_cpp(edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_target_species, min_species, n_hogs, n_genes, max_genes_per_sp, max_missing_edges, w_q, w_eff));
    return rcpp_result_gen;
END_RCPP
}
// find_cliques_stability_cpp
Rcpp::List find_cliques_stability_cpp(IntegerVector edge_hog, IntegerVector edge_g1, IntegerVector edge_g2, IntegerVector edge_sp1, IntegerVector edge_sp2, NumericVector edge_qval, NumericVector edge_eff, int n_all_species, int n_hogs, int n_genes, IntegerVector is_target, Rcpp::List full_cliques, int max_k, int max_genes_per_sp, double jaccard_threshold, int n_cores, double w_q, double w_eff);
RcppExport SEXP _rcomplex_find_cliques_stability_cpp(SEXP edge_hogSEXP, SEXP edge_g1SEXP, SEXP edge_g2SEXP, SEXP edge_sp1SEXP, SEXP edge_sp2SEXP, SEXP edge_qvalSEXP, SEXP edge_effSEXP, SEXP n_all_speciesSEXP, SEXP n_hogsSEXP, SEXP n_genesSEXP, SEXP is_targetSEXP, SEXP full_cliquesSEXP, SEXP max_kSEXP, SEXP max_genes_per_spSEXP, SEXP jaccard_thresholdSEXP, SEXP n_coresSEXP, SEXP w_qSEXP, SEXP w_effSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type edge_hog(edge_hogSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_g1(edge_g1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_g2(edge_g2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_sp1(edge_sp1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_sp2(edge_sp2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_qval(edge_qvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_eff(edge_effSEXP);
    Rcpp::traits::input_parameter< int >::type n_all_species(n_all_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type n_hogs(n_hogsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type is_target(is_targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type full_cliques(full_cliquesSEXP);
    Rcpp::traits::input_parameter< int >::type max_k(max_kSEXP);
    Rcpp::traits::input_parameter< int >::type max_genes_per_sp(max_genes_per_spSEXP);
    Rcpp::traits::input_parameter< double >::type jaccard_threshold(jaccard_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< double >::type w_q(w_qSEXP);
    Rcpp::traits::input_parameter< double >::type w_eff(w_effSEXP);
    rcpp_result_gen = Rcpp::wrap(find_cliques_stability_cpp(edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_all_species, n_hogs, n_genes, is_target, full_cliques, max_k, max_genes_per_sp, jaccard_threshold, n_cores, w_q, w_eff));
    return rcpp_result_gen;
END_RCPP
}
// hog_permutation_test_cpp
Rcpp::DataFrame hog_permutation_test_cpp(const arma::mat& net1, const arma::mat& net2, double thr1, double thr2, const Rcpp::IntegerVector& ortho_sp1_idx, const Rcpp::IntegerVector& ortho_sp2_idx, const Rcpp::List& hog_sp1_list, const Rcpp::List& hog_sp2_list, bool test_greater, int min_exceedances, int max_permutations, int n_cores);
RcppExport SEXP _rcomplex_hog_permutation_test_cpp(SEXP net1SEXP, SEXP net2SEXP, SEXP thr1SEXP, SEXP thr2SEXP, SEXP ortho_sp1_idxSEXP, SEXP ortho_sp2_idxSEXP, SEXP hog_sp1_listSEXP, SEXP hog_sp2_listSEXP, SEXP test_greaterSEXP, SEXP min_exceedancesSEXP, SEXP max_permutationsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type net1(net1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type net2(net2SEXP);
    Rcpp::traits::input_parameter< double >::type thr1(thr1SEXP);
    Rcpp::traits::input_parameter< double >::type thr2(thr2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp1_idx(ortho_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp2_idx(ortho_sp2_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp1_list(hog_sp1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hog_sp2_list(hog_sp2_listSEXP);
    Rcpp::traits::input_parameter< bool >::type test_greater(test_greaterSEXP);
    Rcpp::traits::input_parameter< int >::type min_exceedances(min_exceedancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_permutations(max_permutationsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(hog_permutation_test_cpp(net1, net2, thr1, thr2, ortho_sp1_idx, ortho_sp2_idx, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// module_jaccard_permutation_cpp
Rcpp::DataFrame module_jaccard_permutation_cpp(const Rcpp::IntegerVector& ortho_sp1_gene, const Rcpp::IntegerVector& ortho_sp2_gene, int n_sp1_unique, int n_sp2_universe, const Rcpp::List& mod1_sp1_genes, const Rcpp::List& mod_sp2_sets, const Rcpp::IntegerVector& mod_i_idx, const Rcpp::IntegerVector& mod_j_idx, const Rcpp::NumericVector& obs_jaccard, int min_exceedances, int max_permutations, int n_cores);
RcppExport SEXP _rcomplex_module_jaccard_permutation_cpp(SEXP ortho_sp1_geneSEXP, SEXP ortho_sp2_geneSEXP, SEXP n_sp1_uniqueSEXP, SEXP n_sp2_universeSEXP, SEXP mod1_sp1_genesSEXP, SEXP mod_sp2_setsSEXP, SEXP mod_i_idxSEXP, SEXP mod_j_idxSEXP, SEXP obs_jaccardSEXP, SEXP min_exceedancesSEXP, SEXP max_permutationsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp1_gene(ortho_sp1_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp2_gene(ortho_sp2_geneSEXP);
    Rcpp::traits::input_parameter< int >::type n_sp1_unique(n_sp1_uniqueSEXP);
    Rcpp::traits::input_parameter< int >::type n_sp2_universe(n_sp2_universeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mod1_sp1_genes(mod1_sp1_genesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mod_sp2_sets(mod_sp2_setsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type mod_i_idx(mod_i_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type mod_j_idx(mod_j_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type obs_jaccard(obs_jaccardSEXP);
    Rcpp::traits::input_parameter< int >::type min_exceedances(min_exceedancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_permutations(max_permutationsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(module_jaccard_permutation_cpp(ortho_sp1_gene, ortho_sp2_gene, n_sp1_unique, n_sp2_universe, mod1_sp1_genes, mod_sp2_sets, mod_i_idx, mod_j_idx, obs_jaccard, min_exceedances, max_permutations, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mutual_rank_transform_cached_cpp
arma::mat mutual_rank_transform_cached_cpp(const arma::mat& sim, bool log_transform, int n_cores);
RcppExport SEXP _rcomplex_mutual_rank_transform_cached_cpp(SEXP simSEXP, SEXP log_transformSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transform(log_transformSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mutual_rank_transform_cached_cpp(sim, log_transform, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// compare_neighborhoods_cpp
Rcpp::DataFrame compare_neighborhoods_cpp(const arma::mat& net1, const arma::mat& net2, double thr1, double thr2, const Rcpp::IntegerVector& pair_sp1_idx, const Rcpp::IntegerVector& pair_sp2_idx, const Rcpp::IntegerVector& ortho_sp1_idx, const Rcpp::IntegerVector& ortho_sp2_idx, int n_cores);
RcppExport SEXP _rcomplex_compare_neighborhoods_cpp(SEXP net1SEXP, SEXP net2SEXP, SEXP thr1SEXP, SEXP thr2SEXP, SEXP pair_sp1_idxSEXP, SEXP pair_sp2_idxSEXP, SEXP ortho_sp1_idxSEXP, SEXP ortho_sp2_idxSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type net1(net1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type net2(net2SEXP);
    Rcpp::traits::input_parameter< double >::type thr1(thr1SEXP);
    Rcpp::traits::input_parameter< double >::type thr2(thr2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_sp1_idx(pair_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_sp2_idx(pair_sp2_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp1_idx(ortho_sp1_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ortho_sp2_idx(ortho_sp2_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_neighborhoods_cpp(net1, net2, thr1, thr2, pair_sp1_idx, pair_sp2_idx, ortho_sp1_idx, ortho_sp2_idx, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// reduce_orthogroups_cpp
List reduce_orthogroups_cpp(const arma::mat& expr, const List& hog_members, const IntegerVector& non_hog_idx, double cor_threshold);
RcppExport SEXP _rcomplex_reduce_orthogroups_cpp(SEXP exprSEXP, SEXP hog_membersSEXP, SEXP non_hog_idxSEXP, SEXP cor_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< const List& >::type hog_members(hog_membersSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type non_hog_idx(non_hog_idxSEXP);
    Rcpp::traits::input_parameter< double >::type cor_threshold(cor_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_orthogroups_cpp(expr, hog_members, non_hog_idx, cor_threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcomplex_apply_clr_to_cor_cpp", (DL_FUNC) &_rcomplex_apply_clr_to_cor_cpp, 2},
    {"_rcomplex_build_coclassification_cpp", (DL_FUNC) &_rcomplex_build_coclassification_cpp, 3},
    {"_rcomplex_build_sparse_coclassification_cpp", (DL_FUNC) &_rcomplex_build_sparse_coclassification_cpp, 4},
    {"_rcomplex_sparse_excess_spectral_norm_cpp", (DL_FUNC) &_rcomplex_sparse_excess_spectral_norm_cpp, 4},
    {"_rcomplex_density_threshold_cpp", (DL_FUNC) &_rcomplex_density_threshold_cpp, 2},
    {"_rcomplex_fe_hog_permutation_test_cpp", (DL_FUNC) &_rcomplex_fe_hog_permutation_test_cpp, 7},
    {"_rcomplex_find_cliques_cpp", (DL_FUNC) &_rcomplex_find_cliques_cpp, 15},
    {"_rcomplex_find_cliques_stability_cpp", (DL_FUNC) &_rcomplex_find_cliques_stability_cpp, 18},
    {"_rcomplex_hog_permutation_test_cpp", (DL_FUNC) &_rcomplex_hog_permutation_test_cpp, 12},
    {"_rcomplex_module_jaccard_permutation_cpp", (DL_FUNC) &_rcomplex_module_jaccard_permutation_cpp, 12},
    {"_rcomplex_mutual_rank_transform_cached_cpp", (DL_FUNC) &_rcomplex_mutual_rank_transform_cached_cpp, 3},
    {"_rcomplex_compare_neighborhoods_cpp", (DL_FUNC) &_rcomplex_compare_neighborhoods_cpp, 9},
    {"_rcomplex_reduce_orthogroups_cpp", (DL_FUNC) &_rcomplex_reduce_orthogroups_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcomplex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
