# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply CLR transformation to a correlation matrix
#'
#' Normalizes a correlation matrix using the Context Likelihood Ratio (CLR)
#' transformation (Faith et al. 2007). Computes row z-scores, clamps negatives
#' to zero, and combines row and column z-scores.
#'
#' @param cor_matrix Symmetric correlation matrix (n x n)
#' @param n_cores Number of OpenMP threads (default: 1)
#' @return CLR-transformed matrix (n x n), symmetric, non-negative
#'
#' @details
#' The CLR transformation:
#' \preformatted{
#' z_row(i,j) = (cor(i,j) - mean(row_i)) / sd(row_i)
#' z_col(i,j) = (cor(i,j) - mean(col_j)) / sd(col_j)
#' CLR(i,j) = sqrt(max(0, z_row)^2 + max(0, z_col)^2)
#' }
#'
#' This matches the original RComPlEx Rmd CLR implementation which uses
#' R's scale() function (column-wise z-scoring on the symmetric matrix,
#' equivalent to row-wise z-scoring due to symmetry).
#'
#' @keywords internal
apply_clr_to_cor_cpp <- function(cor_matrix, n_cores = 1L) {
    .Call(`_rcomplex_apply_clr_to_cor_cpp`, cor_matrix, n_cores)
}

#' Build co-classification matrix with per-pair excess
#'
#' @param memberships List of K IntegerVectors (1-based module IDs)
#' @param n_genes Number of genes (N)
#' @param return_excess If TRUE, return excess (adaptive path).
#'   If FALSE, return raw co-classification (fixed threshold path).
#'   Only one N x N matrix is returned, saving ~4.6 GB for N = 24k.
#' @return List with one of coclassification or excess_coclassification,
#'   plus expected (length-K per-resolution expected scalars)
#' @keywords internal
build_coclassification_cpp <- function(memberships, n_genes, return_excess = TRUE) {
    .Call(`_rcomplex_build_coclassification_cpp`, memberships, n_genes, return_excess)
}

#' Sparse co-classification restricted to original network edges
#'
#' Computes co-classification and per-pair excess only for gene pairs
#' connected in the thresholded co-expression network, reducing memory
#' from O(N^2) to O(|E|).
#'
#' @param memberships List of K IntegerVectors (1-based module IDs)
#' @param n_genes Number of genes (N)
#' @param edges |E| x 2 IntegerMatrix of 0-based vertex indices
#' @return List with from, to (0-based), coclassification, excess,
#'   and expected (length-K per-resolution expected scalars)
#' @keywords internal
build_sparse_coclassification_cpp <- function(memberships, n_genes, edges, n_cores = 1L) {
    .Call(`_rcomplex_build_sparse_coclassification_cpp`, memberships, n_genes, edges, n_cores)
}

#' Leading eigenvalue of sparse excess co-classification matrix
#'
#' Computes the spectral norm (largest eigenvalue) of the excess
#' co-classification matrix restricted to the original edge set.
#' Used for the K = 1 community structure test.
#'
#' @param memberships List of K IntegerVectors (1-based module IDs)
#' @param n_genes Number of genes (N)
#' @param edges |E| x 2 IntegerMatrix of 0-based vertex indices
#' @return Leading eigenvalue (non-negative scalar)
#' @keywords internal
sparse_excess_spectral_norm_cpp <- function(memberships, n_genes, edges, n_cores = 1L) {
    .Call(`_rcomplex_sparse_excess_spectral_norm_cpp`, memberships, n_genes, edges, n_cores)
}

#' Compute density threshold from a symmetric matrix
#'
#' Extracts the upper triangle (excluding diagonal) and finds the value at
#' the given density percentile using O(n) partial sort.
#'
#' @param mat Symmetric matrix (n x n)
#' @param density Fraction of top edges to keep (e.g., 0.03 for 3%)
#' @return The threshold value such that `density` fraction of upper triangle
#'   values are >= the threshold
#'
#' @keywords internal
density_threshold_cpp <- function(mat, density) {
    .Call(`_rcomplex_density_threshold_cpp`, mat, density)
}

#' Permutation test using precomputed fold-enrichment matrix
#'
#' @param combined Precomputed combined FE matrix (n1 x n2), where
#'   combined\[a, b\] = FE1(b->a) + FE2(a->b).
#' @param hog_sp1_list List of 0-based sp1 gene indices per HOG
#' @param hog_sp2_list List of 0-based sp2 gene indices per HOG
#' @param test_greater If TRUE, test conservation (T >= T_obs)
#' @param min_exceedances Besag-Clifford stopping parameter
#' @param max_permutations Maximum permutations per HOG
#' @param n_cores Number of OpenMP threads
#' @return DataFrame with T_obs, n_perm, n_exceed, p_value per HOG
#'
#' @keywords internal
fe_hog_permutation_test_cpp <- function(combined, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores) {
    .Call(`_rcomplex_fe_hog_permutation_test_cpp`, combined, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores)
}

#' Find co-expression cliques using two-level decomposition
#'
#' @param edge_hog 0-based HOG index per edge
#' @param edge_g1  0-based gene index for gene 1
#' @param edge_g2  0-based gene index for gene 2
#' @param edge_sp1 0-based species index for gene 1
#' @param edge_sp2 0-based species index for gene 2
#' @param edge_qval q-value per edge
#' @param edge_eff Effect size per edge
#' @param n_target_species Number of target species
#' @param min_species Minimum species for a valid clique
#' @param n_hogs Total number of distinct HOGs
#' @param n_genes Total number of distinct genes
#' @param max_genes_per_sp Maximum genes per species per HOG (default 10)
#' @param max_missing_edges Maximum missing edges tolerated (default 0)
#' @return List with: hog_idx (0-based), genes (matrix, 0-based or NA),
#'   n_species, mean_q, max_q, mean_effect_size, n_edges, n_missing
#' @keywords internal
find_cliques_cpp <- function(edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_target_species, min_species, n_hogs, n_genes, max_genes_per_sp = 10L, max_missing_edges = 0L) {
    .Call(`_rcomplex_find_cliques_cpp`, edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_target_species, min_species, n_hogs, n_genes, max_genes_per_sp, max_missing_edges)
}

#' Leave-k-out jackknife stability for trait-exclusive cliques
#'
#' @param edge_hog,edge_g1,edge_g2,edge_sp1,edge_sp2 0-based edge vectors
#' @param edge_qval,edge_eff per-edge q-value and effect size
#' @param n_all_species total species in the analysis universe
#' @param n_hogs,n_genes total HOGs and genes
#' @param species_trait trait value per species (length n_all_species)
#' @param is_target 1/0 per species (length n_all_species): target membership
#' @param full_cliques output of find_cliques_cpp on the full dataset
#' @param max_k,max_genes_per_sp,jaccard_threshold,n_cores tuning parameters
#' @return List with stability, clique_disruption, stability_class, novel_cliques
#' @keywords internal
find_cliques_stability_cpp <- function(edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_all_species, n_hogs, n_genes, species_trait, is_target, full_cliques, max_k = 3L, max_genes_per_sp = 10L, jaccard_threshold = 0.8, n_cores = 1L) {
    .Call(`_rcomplex_find_cliques_stability_cpp`, edge_hog, edge_g1, edge_g2, edge_sp1, edge_sp2, edge_qval, edge_eff, n_all_species, n_hogs, n_genes, species_trait, is_target, full_cliques, max_k, max_genes_per_sp, jaccard_threshold, n_cores)
}

#' Permutation-based HOG-level conservation test
#'
#' Tests each HOG for co-expression conservation using a gene-identity
#' permutation null with adaptive stopping (Besag & Clifford, 1991).
#'
#' @param net1 Co-expression network matrix for species 1 (n1 x n1)
#' @param net2 Co-expression network matrix for species 2 (n2 x n2)
#' @param thr1 Co-expression threshold for species 1
#' @param thr2 Co-expression threshold for species 2
#' @param ortho_sp1_idx 0-based net1 indices for full ortholog table
#' @param ortho_sp2_idx 0-based net2 indices for full ortholog table
#' @param hog_sp1_list List of integer vectors: unique 0-based sp1 indices per HOG
#' @param hog_sp2_list List of integer vectors: unique 0-based sp2 indices per HOG
#' @param test_greater If TRUE, test conservation (T >= T_obs); if FALSE, divergence
#' @param min_exceedances Besag-Clifford stopping parameter (default 50)
#' @param max_permutations Maximum permutations per HOG (default 10000)
#' @param n_cores Number of OpenMP threads (default 1)
#' @return DataFrame with T_obs, n_perm, n_exceed, p_value per HOG
#'
#' @keywords internal
hog_permutation_test_cpp <- function(net1, net2, thr1, thr2, ortho_sp1_idx, ortho_sp2_idx, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores) {
    .Call(`_rcomplex_hog_permutation_test_cpp`, net1, net2, thr1, thr2, ortho_sp1_idx, ortho_sp2_idx, hog_sp1_list, hog_sp2_list, test_greater, min_exceedances, max_permutations, n_cores)
}

#' Permutation-based Jaccard test for module comparison (batched)
#'
#' Tests each module pair for significant Jaccard overlap using ortholog-mapping
#' permutation with Besag-Clifford adaptive stopping.  Uses batched permutation:
#' one shuffle per iteration shared across all active pairs.
#'
#' @param ortho_sp1_gene 0-based index of each ortholog's sp1 unique gene
#' @param ortho_sp2_gene 0-based sp2 gene index for each ortholog row
#' @param n_sp1_unique Number of unique sp1 genes in ortholog table
#' @param n_sp2_universe Total number of sp2 genes in index space
#' @param mod1_sp1_genes List of integer vectors: sp1 unique gene indices per sp1 module
#' @param mod_sp2_sets List of integer vectors: sp2 indices per sp2 module
#' @param mod_i_idx 0-based index into mod1_sp1_genes for each pair
#' @param mod_j_idx 0-based index into mod_sp2_sets for each pair
#' @param obs_jaccard Observed Jaccard for each pair
#' @param min_exceedances Besag-Clifford stopping parameter
#' @param max_permutations Maximum permutations
#' @param n_cores Number of OpenMP threads
#' @return DataFrame with n_perm, n_exceed, p_value per pair
#'
#' @keywords internal
module_jaccard_permutation_cpp <- function(ortho_sp1_gene, ortho_sp2_gene, n_sp1_unique, n_sp2_universe, mod1_sp1_genes, mod_sp2_sets, mod_i_idx, mod_j_idx, obs_jaccard, min_exceedances, max_permutations, n_cores) {
    .Call(`_rcomplex_module_jaccard_permutation_cpp`, ortho_sp1_gene, ortho_sp2_gene, n_sp1_unique, n_sp2_universe, mod1_sp1_genes, mod_sp2_sets, mod_i_idx, mod_j_idx, obs_jaccard, min_exceedances, max_permutations, n_cores)
}

#' Cached mutual rank transformation
#'
#' Transforms a correlation matrix using mutual rank normalization.
#'
#' @param sim Symmetric correlation/similarity matrix (n x n)
#' @param log_transform If FALSE (default), uses raw mutual rank with ascending
#'   ranks (original Rmd formula). If TRUE, applies Obayashi & Kinoshita (2009)
#'   log-normalized formula with descending ranks (values in 0 to 1 range).
#' @param n_cores Number of OpenMP threads (default: 1)
#' @return Mutual rank normalized matrix (n x n)
#'
#' @details
#' When `log_transform = TRUE`:
#' \deqn{S_{ij} = 1 - \log(\sqrt{R_{ij} \cdot R_{ji}}) / \log(n)}
#' where ranks are descending (highest correlation = rank 1).
#'
#' When `log_transform = FALSE`:
#' \deqn{MR_{ij} = \sqrt{R_{ij} \cdot R_{ji}}}
#' where ranks are ascending (lowest correlation = rank 1), matching the
#' original RComPlEx R Markdown formula.
#'
#' @keywords internal
mutual_rank_transform_cached_cpp <- function(sim, log_transform = FALSE, n_cores = 1L) {
    .Call(`_rcomplex_mutual_rank_transform_cached_cpp`, sim, log_transform, n_cores)
}

#' Compare co-expression neighborhoods across species (integer-indexed)
#'
#' For each ortholog pair, tests the overlap of co-expression neighborhoods
#' in both directions (sp1->sp2 and sp2->sp1) using hypergeometric tests.
#' All gene identifiers are 0-based integer indices (string mapping done in R).
#'
#' @param net1 Co-expression network for species 1 (n1 x n1 matrix)
#' @param net2 Co-expression network for species 2 (n2 x n2 matrix)
#' @param thr1 Co-expression threshold for species 1
#' @param thr2 Co-expression threshold for species 2
#' @param pair_sp1_idx 0-based index into net1 for each ortholog pair
#' @param pair_sp2_idx 0-based index into net2 for each ortholog pair
#' @param ortho_sp1_idx 0-based net1 indices for full ortholog table
#' @param ortho_sp2_idx 0-based net2 indices for full ortholog table
#' @param n_cores Number of OpenMP threads (default: 1)
#' @return DataFrame with comparison results for each ortholog pair
#'
#' @keywords internal
compare_neighborhoods_cpp <- function(net1, net2, thr1, thr2, pair_sp1_idx, pair_sp2_idx, ortho_sp1_idx, ortho_sp2_idx, n_cores = 1L) {
    .Call(`_rcomplex_compare_neighborhoods_cpp`, net1, net2, thr1, thr2, pair_sp1_idx, pair_sp2_idx, ortho_sp1_idx, ortho_sp2_idx, n_cores)
}

#' Reduce orthogroups by merging correlated paralogs
#'
#' For each HOG with multiple paralogs, computes pairwise Pearson correlation
#' on the expression matrix, clusters with Ward.D2, and merges paralogs
#' whose correlation exceeds \code{cor_threshold} into a single averaged
#' representative.
#'
#' @param expr Numeric matrix (genes x samples). Row order matches gene_ids.
#' @param hog_members List of integer vectors. Each element contains 1-indexed
#'   row positions in \code{expr} for genes belonging to one HOG.
#' @param non_hog_idx Integer vector of 1-indexed row positions for genes
#'   not assigned to any HOG (kept as-is).
#' @param cor_threshold Pearson correlation threshold for merging (default 0.7).
#' @return List with: expr_matrix (reduced matrix), out_row_source (1-indexed
#'   original row for each output row), map_from / map_to (1-indexed gene
#'   mapping), n_original, n_reduced, n_merged.
#' @keywords internal
reduce_orthogroups_cpp <- function(expr, hog_members, non_hog_idx, cor_threshold) {
    .Call(`_rcomplex_reduce_orthogroups_cpp`, expr, hog_members, non_hog_idx, cor_threshold)
}

